<?php /* Smarty version 2.6.25, created on 2011-07-28 15:20:31
         compiled from siteprefs.tpl */

$this->_cache_serials['/var/www/madesimple/tmp/templates_c/%%1B^1B2^1B2DE232%%siteprefs.tpl.inc'] = '93bfc4ab8ff59f5bab9bd5cc74a44871';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'html_options', 'siteprefs.tpl', 26, false),array('modifier', 'lang', 'siteprefs.tpl', 101, false),)), $this); ?>
<?php
function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','0');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['wysiwyg'],'selected' => $_smarty->_tpl_vars['frontendwysiwyg']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','1');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['themes'],'selected' => $_smarty->_tpl_vars['logintheme']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','2');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['titlemenu'],'selected' => $_smarty->_tpl_vars['listcontent_showtitle']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','3');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['listcontent_showalias']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','4');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['listcontent_showurl']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','5');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_autocreate_urls']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','6');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_autocreate_flaturls']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_7(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','7');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['yesno'],'selected' => $_smarty->_tpl_vars['content_mandatory_urls']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_8(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','8');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['all_attributes'],'selected' => $_smarty->_tpl_vars['basic_attributes']), $_smarty);
}


function _smarty_tplfunc_93bfc4ab8ff59f5bab9bd5cc74a44871_9(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('93bfc4ab8ff59f5bab9bd5cc74a44871','9');echo smarty_function_html_options(array('options' => $_smarty->_tpl_vars['pseudocron_options'],'selected' => $_smarty->_tpl_vars['pseudocron_granularity']), $_smarty);
}



?>
