<?php /* Smarty version 2.6.25, created on 2011-08-02 14:57:56
         compiled from tpl_head:15 */

$this->_cache_serials['/var/www/madesimple/tmp/templates_c/%%AC^AC0^AC0087CA%%tpl_head%3A15.inc'] = 'ed5b74b0e72c4e42e5e5684f2c3d21cf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'sitename', 'tpl_head:15', 2, false),array('function', 'title', 'tpl_head:15', 2, false),array('function', 'metadata', 'tpl_head:15', 5, false),array('function', 'cms_stylesheet', 'tpl_head:15', 8, false),array('function', 'cms_selflink', 'tpl_head:15', 11, false),)), $this); ?>
<?php
function _smarty_tplfunc_ed5b74b0e72c4e42e5e5684f2c3d21cf_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed5b74b0e72c4e42e5e5684f2c3d21cf','0');echo smarty_cms_function_sitename(array(), $_smarty);
}


function _smarty_tplfunc_ed5b74b0e72c4e42e5e5684f2c3d21cf_1(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed5b74b0e72c4e42e5e5684f2c3d21cf','1');echo smarty_cms_function_title(array(), $_smarty);
}


function _smarty_tplfunc_ed5b74b0e72c4e42e5e5684f2c3d21cf_2(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed5b74b0e72c4e42e5e5684f2c3d21cf','2');echo smarty_cms_function_metadata(array(), $_smarty);
}


function _smarty_tplfunc_ed5b74b0e72c4e42e5e5684f2c3d21cf_3(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed5b74b0e72c4e42e5e5684f2c3d21cf','3');echo smarty_cms_function_cms_stylesheet(array(), $_smarty);
}


function _smarty_tplfunc_ed5b74b0e72c4e42e5e5684f2c3d21cf_4(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed5b74b0e72c4e42e5e5684f2c3d21cf','4');echo smarty_cms_function_cms_selflink(array('dir' => 'start','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_ed5b74b0e72c4e42e5e5684f2c3d21cf_5(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed5b74b0e72c4e42e5e5684f2c3d21cf','5');echo smarty_cms_function_cms_selflink(array('dir' => 'prev','rellink' => 1), $_smarty);
}


function _smarty_tplfunc_ed5b74b0e72c4e42e5e5684f2c3d21cf_6(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('ed5b74b0e72c4e42e5e5684f2c3d21cf','6');echo smarty_cms_function_cms_selflink(array('dir' => 'next','rellink' => 1), $_smarty);
}



?>
