<?php /* Smarty version 2.6.25, created on 2011-08-02 14:57:56
         compiled from tpl_top:15 */

$this->_cache_serials['/var/www/madesimple/tmp/templates_c/%%E7^E7A^E7AE0EEB%%tpl_top%3A15.inc'] = '4ccb4b49ea9e92a0a7c0f4c6bf8f9d2b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'process_pagedata', 'tpl_top:15', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_4ccb4b49ea9e92a0a7c0f4c6bf8f9d2b_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('4ccb4b49ea9e92a0a7c0f4c6bf8f9d2b','0');echo smarty_cms_function_process_pagedata(array(), $_smarty);
}



?>
