<?php /* Smarty version 2.6.25, created on 2011-07-28 15:36:08
         compiled from content:content_en */

$this->_cache_serials['/var/www/madesimple/tmp/templates_c/58^%%70^707^707A8977%%content%3Acontent_en.inc'] = 'da8e75276f313d9bbd6f31b2b3c40c75';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cms_module', 'content:content_en', 1, false),)), $this); ?>
<?php
function _smarty_tplfunc_da8e75276f313d9bbd6f31b2b3c40c75_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('da8e75276f313d9bbd6f31b2b3c40c75','0');echo smarty_cms_function_cms_module(array('module' => 'Album'), $_smarty);
}



?>
