<?php /* Smarty version 2.6.25, created on 2011-07-28 15:47:22
         compiled from module_file_tpl:Album%3Bcategorylist.tpl */

$this->_cache_serials['/var/www/madesimple/tmp/templates_c/Album^%%FC^FC3^FC313757%%module_file_tpl%3AAlbum%3Bcategorylist.tpl.inc'] = '36e9afa15083a6e95687cd44eafce25c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'cycle', 'module_file_tpl:Album;categorylist.tpl', 15, false),)), $this); ?>
<?php
function _smarty_tplfunc_36e9afa15083a6e95687cd44eafce25c_0(&$_smarty)
{
$_cache_attrs =& $_smarty->_smarty_cache_attrs('36e9afa15083a6e95687cd44eafce25c','0');echo smarty_function_cycle(array('values' => "row1,row2",'assign' => 'rowclass'), $_smarty);
}



?>
